[package]
name = "rust_flutter_application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-multipart = "0.6.1"
actix-web = "4.4.1"
argon2 = "0.5.3"
async-trait = "0.1.77"
base64 = "0.22.0"
chrono = { version = "0.4.31", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.11.0"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
# openssl = { version = "0.10.64", features = ["vendored"] }
# openssl-probe = "0.1.5"
redis = { version = "0.24.0", features = ["tokio-comp"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sqlx = { version = "0.7.3", features = [
    "runtime-async-std-native-tls",
    "mysql",
    "chrono",
    "uuid",
] }
utoipa = { version = "4.2.0", features = ["chrono", "actix_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }
