version: '3'
name: rust_flutter_application

services:
  mysql:
    image: mysql:8.3.0
    container_name: rfa_mysql
    env_file:
      - ./.env
    ports:
      - '6500:3306'
    volumes:
      - rfa_mysql_volume:/var/lib/mysql
    networks:
      - rust_app_no_api_network
volumes:
  rfa_mysql_volume:
networks:
  rust_app_no_api_network:
