version: '3'
name: rust_flutter_application

services:
  mysql:
    image: mysql:8.3.0
    container_name: rfa_mysql_db
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '6500:3306'
    volumes:
      - rfa_mysql_volume:/var/lib/mysql
  redis:
    image: redis:alpine3.17
    container_name: rfa_redis_db
    ports:
      - '6379:6379'
    volumes:
      - rfa_redis_volume:/data
volumes:
  rfa_mysql_volume:
  rfa_redis_volume:
